api_platform:
    metadata_backward_compatibility_layer: false
    mapping:
        paths:
            - '%kernel.project_dir%/src/Infrastructure/Authentication/ApiPlatform/Resource/'
    patch_formats:
        json: ['application/merge-patch+json']
    swagger:
        versions: [3]

    exception_to_status:
        Webmozart\Assert\InvalidArgumentException: 422
