framework:
    messenger:
        default_bus: command.bus

        buses:
            command.bus: []
            query.bus: []

        transports:
            sync: 'sync://'

        routing:
            'App\Application\Shared\Query\QueryInterface': sync

        reset_on_message: true
